import type { ToneKey } from '@/lib/types';

export const TONE: Record<string, ToneKey> = {
  active: 'success',
  draft: 'neutral',
  low_stock: 'warn',
  out_of_stock: 'danger',
  pending: 'warn',
  processing: 'info',
  shipped: 'info',
  delivered: 'success',
  cancelled: 'danger',
  paid: 'success',
  unpaid: 'warn',
  refunded: 'neutral',
  requested: 'warn',
  approved: 'info',
  received: 'info',
  rejected: 'danger',
  locked: 'danger',
  vip: 'info',
  regular: 'neutral',
  published: 'success',
  hero: 'info',
  announcement: 'warn',
  popup: 'neutral',
  footer: 'neutral',
  percent: 'info',
  fixed: 'neutral',
  true: 'success',
  false: 'neutral',
  production: 'success',
  sandbox: 'warn',
  ready: 'success',
  pending_setup: 'warn',
};

export const LABEL: Record<string, string> = {
  active: '上架',
  draft: '草稿',
  low_stock: '低庫存',
  out_of_stock: '缺貨',
  pending: '待處理',
  processing: '處理中',
  shipped: '已出貨',
  delivered: '已送達',
  cancelled: '已取消',
  paid: '已付款',
  unpaid: '未付款',
  refunded: '已退款',
  requested: '待審',
  approved: '已核准',
  received: '已收件',
  rejected: '已駁回',
  locked: '已鎖定',
  vip: 'VIP',
  regular: '一般',
  published: '已發布',
  hero: 'Hero',
  announcement: '公告',
  popup: 'Popup',
  footer: 'Footer',
  percent: '百分比',
  fixed: '定額',
  true: '啟用',
  false: '停用',
  production: '正式',
  sandbox: '測試',
  ready: '就緒',
  pending_setup: '待設定',
};
